from flask import Flask, render_template, request
import datetime

app = Flask(__name__)

def calculate_metrics(revenue, units_sold, selling_price, cost_of_goods_sold, operating_expenses, interest, taxes, period):

    average_revenue = revenue / units_sold
    operating_cost = cost_of_goods_sold + operating_expenses
    gross_profit = revenue - cost_of_goods_sold
    gross_profit_margin_rate = (gross_profit / revenue) * 100
    operating_profit_margin_rate = ((gross_profit - operating_expenses) / revenue) * 100
    net_profit_margin_rate = (((gross_profit - operating_expenses) - (interest + taxes)) / revenue) * 100
    return_of_investment = (((gross_profit - operating_expenses) - (interest + taxes)) / (cost_of_goods_sold + operating_expenses)) * 100

    if period == 'daily':
        time_factor = 1
        average_revenue = revenue / units_sold
        operating_cost = cost_of_goods_sold + operating_expenses
        gross_profit = revenue - cost_of_goods_sold
        gross_profit_margin_rate = (gross_profit / revenue) * 100
        operating_profit_margin_rate = ((gross_profit - operating_expenses) / revenue) * 100
        net_profit_margin_rate = (((gross_profit - operating_expenses) - (interest + taxes)) / revenue) * 100
        return_of_investment = (((gross_profit - operating_expenses) - (interest + taxes)) / (cost_of_goods_sold + operating_expenses)) * 100
    elif period == 'monthly':
        time_factor = 30
        average_revenue = (revenue / units_sold) * 30
        operating_cost = (cost_of_goods_sold + operating_expenses) * 30
        gross_profit = (revenue - cost_of_goods_sold) * 30
        gross_profit_margin_rate = ((gross_profit / revenue) * 100) * 30
        operating_profit_margin_rate = (((gross_profit - operating_expenses) / revenue) * 100) * 30
        net_profit_margin_rate = ((((gross_profit - operating_expenses) - (interest + taxes)) / revenue) * 100) * 30
        return_of_investment = ((((gross_profit - operating_expenses) - (interest + taxes)) / (cost_of_goods_sold + operating_expenses)) * 100) * 30
    else:
        time_factor = 365
        average_revenue = (revenue / units_sold) * 365
        operating_cost = (cost_of_goods_sold + operating_expenses) * 365
        gross_profit = (revenue - cost_of_goods_sold) * 365
        gross_profit_margin_rate = ((gross_profit / revenue) * 100) * 365
        operating_profit_margin_rate = (((gross_profit - operating_expenses) / revenue) * 100) * 365
        net_profit_margin_rate = ((((gross_profit - operating_expenses) - (interest + taxes)) / revenue) * 100) * 365
        return_of_investment = ((((gross_profit - operating_expenses) - (interest + taxes)) / (cost_of_goods_sold + operating_expenses)) * 100) * 365

    return {
        'average_revenue': format(average_revenue, '.2f'),
        'operating_cost': format(operating_cost, '.2f'),
        'gross_profit': format(gross_profit, '.2f'),
        'gross_profit_margin_rate': format(gross_profit_margin_rate, '.2f'),
        'operating_profit_margin_rate': format(operating_profit_margin_rate, '.2f'),
        'net_profit_margin_rate': format(net_profit_margin_rate, '.2f'),
        'return_of_investment': format(return_of_investment, '2f'),
    }
def fetch_descriptions(nationality):
    descriptions = {
    'en': {
        'currency_symbol': '$',
        'average_revenue': "The total income generated by a business divided by the number of units sold or services provided.",
        'operating_cost': "The total expenses incurred by a business in its day-to-day operations, including both fixed and variable costs.",
        'gross_profit': "The difference between total revenue and the cost of goods sold, representing the profit before deducting other expenses.",
        'gross_profit_margin_rate': "The percentage of revenue that exceeds the cost of goods sold, indicating the profitability of a business's core operations.",
        'operating_profit_margin_rate': "The percentage of profit remaining after deducting operating expenses from gross profit, reflecting operational efficiency.",
        'net_profit_margin_rate': "The percentage of profit remaining after deducting all expenses, including operating expenses, interest, taxes, and other costs.",
        'return_of_investment': "A measure of the profitability of an investment, expressed as a percentage, calculated by dividing the net profit from the investment by its initial cost."
    },
    'fr': {
        'currency_symbol': '€',
        'average_revenue': "Le revenu total généré par une entreprise divisé par le nombre d'unités vendues ou de services fournis.",
        'operating_cost': "Les dépenses totales engagées par une entreprise dans ses opérations quotidiennes, y compris les coûts fixes et variables.",
        'gross_profit': "La différence entre le chiffre d'affaires total et le coût des marchandises vendues, représentant le profit avant déduction d'autres dépenses.",
        'gross_profit_margin_rate': "Le pourcentage de chiffre d'affaires qui dépasse le coût des marchandises vendues, indiquant la rentabilité des opérations principales d'une entreprise.",
        'operating_profit_margin_rate': "Le pourcentage de profit restant après déduction des dépenses d'exploitation du bénéfice brut, reflétant l'efficacité opérationnelle.",
        'net_profit_margin_rate': "Le pourcentage de profit restant après déduction de toutes les dépenses, y compris les dépenses d'exploitation, les intérêts, les impôts et autres coûts.",
        'return_of_investment': "Une mesure de la rentabilité d'un investissement, exprimée en pourcentage, calculée en divisant le bénéfice net de l'investissement par son coût initial."
    },
    'es': {
        'currency_symbol': '€',
        'average_revenue': "Los ingresos totales generados por un negocio divididos por el número de unidades vendidas o servicios prestados.",
        'operating_cost': "Los gastos totales en los que incurre un negocio en sus operaciones diarias, incluidos los costos fijos y variables.",
        'gross_profit': "La diferencia entre los ingresos totales y el costo de los bienes vendidos, que representa la ganancia antes de deducir otros gastos.",
        'gross_profit_margin_rate': "El porcentaje de ingresos que excede el costo de los bienes vendidos, lo que indica la rentabilidad de las operaciones principales de un negocio.",
        'operating_profit_margin_rate': "El porcentaje de ganancia que queda después de deducir los gastos de operación del beneficio bruto, reflejando la eficiencia operativa.",
        'net_profit_margin_rate': "El porcentaje de ganancia que queda después de deducir todos los gastos, incluidos los gastos de operación, intereses, impuestos y otros costos.",
        'return_of_investment': "Una medida de la rentabilidad de una inversión, expresada como porcentaje, calculada dividiendo la ganancia neta de la inversión por su costo inicial."
    },
    'fil': {
        'currency_symbol': '₱',
        'average_revenue': "Ang kabuuang kita na ginagawa ng isang negosyo na hinati sa bilang ng mga yunit na ibinebenta o serbisyo na ibinibigay.",
        'operating_cost': "Ang kabuuang gastos na ginagastos ng isang negosyo sa araw-araw na operasyon, kabilang ang mga fixed at variable cost.",
        'gross_profit': "Ang pagkakaiba sa pagitan ng kabuuang kita at ang gastos sa mga kalakal na ibinebenta, na kumakatawan sa tubo bago bawasan ang iba pang mga gastos.",
        'gross_profit_margin_rate': "Ang porsyento ng kita na lumampas sa gastos sa mga kalakal na ibinebenta, na nagpapakita ng kahalagahan ng operasyon ng isang negosyo.",
        'operating_profit_margin_rate': "Ang porsyento ng tubo na natitira pagkatapos bawasan ang mga gastos sa operasyon mula sa tubo bago bawasan ang iba pang mga gastos, na nagsasalamin ng kahusayan sa operasyon.",
        'net_profit_margin_rate': "Ang porsyento ng tubo na natitira pagkatapos bawasan ang lahat ng mga gastos, kabilang ang gastos sa operasyon, interes, buwis, at iba pang mga gastos.",
        'return_of_investment': "Isang sukatan ng kahalagahan ng isang investisyon, na nasa anyong porsyento, na kinokonbert ang netong kita mula sa investisyon sa unang gastos nito."
    },
    'fi': {
        'currency_symbol': '€',
        'average_revenue': "Yrityksen tuottama kokonaistulo jaettuna myytyjen yksiköiden tai tarjoiltujen palveluiden määrällä.",
        'operating_cost': "Yrityksen päivittäisessä toiminnassa aiheutuneet kokonaiskulut, mukaan lukien kiinteät ja muuttuvat kustannukset.",
        'gross_profit': "Erotus kokonaistulon ja myytävien tavaroiden kustannusten välillä, edustaen voittoa ennen muiden kulujen vähentämistä.",
        'gross_profit_margin_rate': "Prosenttiosuus tulosta, joka ylittää myytävien tavaroiden kustannukset, osoittaen yrityksen ydintoimintojen kannattavuuden.",
        'operating_profit_margin_rate': "Prosenttiosuus voitosta, joka jää jäljelle vähentämällä toimintakulut bruttovoitosta, heijastaa operatiivista tehokkuutta.",
        'net_profit_margin_rate': "Prosenttiosuus voitosta, joka jää jäljelle vähentämällä kaikki kulut, mukaan lukien toimintakulut, korot, verot ja muut kulut.",
        'return_of_investment': "Sijoituksen kannattavuuden mitta, ilmaistuna prosentteina, lasketaan jakamalla sijoituksen nettotulos sen alkuperäisellä kustannuksella."
    },
    'du': {
        'currency_symbol': '€',
        'average_revenue': "De totale inkomsten die door een bedrijf worden gegenereerd, gedeeld door het aantal verkochte eenheden of verleende diensten.",
        'operating_cost': "De totale kosten die een bedrijf maakt in zijn dagelijkse operaties, inclusief zowel vaste als variabele kosten.",
        'gross_profit': "Het verschil tussen de totale omzet en de kosten van verkochte goederen, wat de winst vertegenwoordigt vóór aftrek van andere kosten.",
        'gross_profit_margin_rate': "Het percentage van de omzet dat de kosten van verkochte goederen overschrijdt, wat de winstgevendheid van de kernactiviteiten van een bedrijf aangeeft.",
        'operating_profit_margin_rate': "Het percentage winst dat overblijft na aftrek van operationele kosten van de brutowinst, wat de operationele efficiëntie weerspiegelt.",
        'net_profit_margin_rate': "Het percentage winst dat overblijft na aftrek van alle kosten, inclusief operationele kosten, rente, belastingen en andere kosten.",
        'return_of_investment': "Een maatstaf voor de winstgevendheid van een investering, uitgedrukt als percentage, berekend door de nettowinst van de investering te delen door de initiële kosten."
    },
    'tu': {
        'currency_symbol': '₺',
        'average_revenue': "Bir işletme tarafından üretilen toplam gelirin satılan birim sayısı veya sağlanan hizmetlerle bölünmesi.",
        'operating_cost': "Bir işletmenin günlük operasyonlarında ortaya çıkan toplam giderler, hem sabit hem de değişken maliyetleri içerir.",
        'gross_profit': "Toplam gelir ile satılan malın maliyeti arasındaki fark, diğer giderlerin düşülmesinden önceki kârı temsil eder.",
        'gross_profit_margin_rate': "Satılan malın maliyetini aşan gelirin yüzdesi, bir işletmenin temel faaliyetlerinin karlılığını gösterir.",
        'operating_profit_margin_rate': "Brüt karın işletme giderlerinden düşülmesinden sonra kalan kârın yüzdesi, işletme verimliliğini yansıtır.",
        'net_profit_margin_rate': "Tüm giderlerin, işletme giderlerinin, faizlerin, vergilerin ve diğer maliyetlerin düşülmesinden sonra kalan kârın yüzdesi.",
        'return_of_investment': "Bir yatırımın karlılığını ölçen, yüzde olarak ifade edilen bir ölçü, yatırımın net kârını başlangıç maliyetine bölen bir hesapla hesaplanır."
    },
    'it': {
        'currency_symbol': '€',
        'average_revenue': "Il reddito totale generato da un'azienda diviso per il numero di unità vendute o servizi resi.",
        'operating_cost': "Le spese totali sostenute da un'azienda nelle sue operazioni quotidiane, comprese sia le spese fisse che variabili.",
        'gross_profit': "La differenza tra il fatturato totale e il costo delle merci vendute, che rappresenta il profitto prima della deduzione di altre spese.",
        'gross_profit_margin_rate': "La percentuale di fatturato che supera il costo delle merci vendute, indicando la redditività delle operazioni principali di un'azienda.",
        'operating_profit_margin_rate': "La percentuale di profitto rimasto dopo la deduzione delle spese operative dal profitto lordo, riflettendo l'efficienza operativa.",
        'net_profit_margin_rate': "La percentuale di profitto rimasto dopo la deduzione di tutte le spese, incluse le spese operative, gli interessi, le tasse e altri costi.",
        'return_of_investment': "Una misura della redditività di un investimento, espressa come percentuale, calcolata dividendo il profitto netto dall'investimento per il suo costo iniziale."
    },
    'ja': {
        'currency_symbol': '¥',
        'average_revenue': "ビジネスが生み出す総収入を販売された単位数または提供されたサービスの数で割ったもの。",
        'operating_cost': "ビジネスが日々の運営で負担する総費用。固定費と変動費の両方が含まれます。",
        'gross_profit': "総収入と売上原価の差額であり、他の経費を差し引く前の利益を表します。",
        'gross_profit_margin_rate': "売上原価を上回る収入の割合で、ビジネスの中核的な業務の収益性を示します。",
        'operating_profit_margin_rate': "売上原価を控除した売上高から残る利益の割合で、運営効率を反映しています。",
        'net_profit_margin_rate': "運営費用、利息、税金、その他の費用を含むすべての経費を控除した後の利益の割合。",
        'return_of_investment': "投資の収益性を示す指標で、パーセンテージで表され、投資の純利益を初期コストで割ったもの。"
    },
    'po': {
        'currency_symbol': '€',
        'average_revenue': "A receita total gerada por um negócio dividida pelo número de unidades vendidas ou serviços prestados.",
        'operating_cost': "Os gastos totais incorridos por um negócio em suas operações do dia a dia, incluindo custos fixos e variáveis.",
        'gross_profit': "A diferença entre a receita total e o custo dos bens vendidos, representando o lucro antes de deduzir outras despesas.",
        'gross_profit_margin_rate': "A porcentagem da receita que excede o custo dos bens vendidos, indicando a lucratividade das operações principais de um negócio.",
        'operating_profit_margin_rate': "A porcentagem de lucro restante após deduzir as despesas operacionais do lucro bruto, refletindo a eficiência operacional.",
        'net_profit_margin_rate': "A porcentagem de lucro restante após deduzir todas as despesas, incluindo despesas operacionais, juros, impostos e outros custos.",
        'return_of_investment': "Uma medida da lucratividade de um investimento, expressa como porcentagem, calculada dividindo o lucro líquido do investimento por seu custo inicial."
    },
    'ch': {
        'currency_symbol': '¥',
        'average_revenue': "企业产生的总收入除以销售的单位数量或提供的服务数量。",
        'operating_cost': "企业在日常运营中产生的总费用，包括固定成本和变动成本。",
        'gross_profit': "总收入与销售商品的成本之间的差额，代表在扣除其他费用之前的利润。",
        'gross_profit_margin_rate': "超过销售商品成本的收入的百分比，表示企业核心运营的盈利能力。",
        'operating_profit_margin_rate': "扣除运营费用后剩余利润与总收入之比，反映了运营效率。",
        'net_profit_margin_rate': "扣除所有费用后剩余的利润占总收入的百分比，包括运营费用、利息、税收和其他成本。",
        'return_of_investment': "投资回报率的衡量标准，以百分比表示，通过将投资的净利润除以初始成本计算。"
    },
    'ge': {
        'currency_symbol': '€',
        'average_revenue': "Die Gesamteinnahmen, die ein Unternehmen durch die Anzahl der verkauften Einheiten oder erbrachten Dienstleistungen erzielt.",
        'operating_cost': "Die Gesamtkosten, die ein Unternehmen in seinem täglichen Betrieb verursacht, einschließlich sowohl fester als auch variabler Kosten.",
        'gross_profit': "Der Unterschied zwischen dem Gesamtumsatz und den Kosten der verkauften Waren, der den Gewinn vor Abzug anderer Ausgaben darstellt.",
        'gross_profit_margin_rate': "Der Prozentsatz des Umsatzes, der die Kosten der verkauften Waren übersteigt, was die Rentabilität der Kernaktivitäten eines Unternehmens anzeigt.",
        'operating_profit_margin_rate': "Der Prozentsatz des Gewinns, der nach Abzug der Betriebskosten vom Bruttogewinn übrig bleibt und die betriebliche Effizienz widerspiegelt.",
        'net_profit_margin_rate': "Der Prozentsatz des Gewinns, der nach Abzug aller Kosten, einschließlich Betriebskosten, Zinsen, Steuern und sonstiger Kosten, übrig bleibt.",
        'return_of_investment': "Ein Maß für die Rentabilität einer Investition, ausgedrückt als Prozentsatz, berechnet durch die Division des Nettogewinns aus der Investition durch ihre anfänglichen Kosten."
    },
    'br': {
        'currency_symbol': 'R$',
        'average_revenue': "A receita total gerada por um negócio dividida pelo número de unidades vendidas ou serviços prestados.",
        'operating_cost': "Os custos totais incorridos por um negócio em suas operações diárias, incluindo custos fixos e variáveis.",
        'gross_profit': "A diferença entre a receita total e o custo dos bens vendidos, representando o lucro antes de deduzir outras despesas.",
        'gross_profit_margin_rate': "A porcentagem da receita que excede o custo dos bens vendidos, indicando a lucratividade das operações principais de um negócio.",
        'operating_profit_margin_rate': "A porcentagem de lucro restante após deduzir as despesas operacionais do lucro bruto, refletindo a eficiência operacional.",
        'net_profit_margin_rate': "A porcentagem de lucro restante após deduzir todas as despesas, incluindo despesas operacionais, juros, impostos e outros custos.",
        'return_of_investment': "Uma medida da lucratividade de um investimento, expressa como porcentagem, calculada dividindo o lucro líquido do investimento por seu custo inicial."
    },
    'hi': {
        'currency_symbol': '₹',
        'average_revenue': "व्यापार द्वारा उत्पन्न कुल आय जो यूनिट बेचे या सेवाएं प्रदान की गई हैं के संख्या से बाँटी गई।",
        'operating_cost': "एक व्यापार की दिन की दिन की ऑपरेशन्स में उत्पन्न कुल खर्च, स्थिर और बदलते लागतों समेत।",
        'gross_profit': "कुल आय और बेची गई वस्त्रों की लागत के बीच का अंतर, अन्य व्ययों को कटाने से पहले लाभ को प्रतिनिधित्विता करता है।",
        'gross_profit_margin_rate': "आय का प्रतिशत जो बेची गई वस्त्रों की लागत से अधिक होता है, जो व्यापार की मुख्य ऑपरेशन की लाभकारिता को दर्शाता है।",
        'operating_profit_margin_rate': "ग्रॉस लाभ से ऑपरेशनल खर्चों को कटाने के बाद शेष लाभ का प्रतिशत, ऑपरेशनल प्रभावकारिता को प्रतिबिम्बित करता है।",
        'net_profit_margin_rate': "सभी व्ययों, संचालन व्यय, ब्याज, कर और अन्य लागतों को छोड़कर शेष लाभ का प्रतिशत।",
        'return_of_investment': "निवेश की लाभकारिता का माप, प्रतिशत में व्यक्त किया गया, निवेश के निकटतम लागत से निवेश की शुद्ध लाभ द्वारा विभाजित करके की गई है।"
    },
    'ru': {
        'currency_symbol': '₽',
        'average_revenue': "Общий доход, полученный компанией, делится на количество проданных единиц или предоставленных услуг.",
        'operating_cost': "Общие затраты, понесенные компанией в ее повседневной деятельности, включая как фиксированные, так и переменные затраты.",
        'gross_profit': "Разница между общим доходом и затратами на проданные товары, представляющая прибыль до вычета других расходов.",
        'gross_profit_margin_rate': "Процент дохода, который превышает затраты на проданные товары, указывая на прибыльность основных операций компании.",
        'operating_profit_margin_rate': "Процент прибыли, оставшейся после вычета операционных расходов из валовой прибыли, отражающей операционную эффективность.",
        'net_profit_margin_rate': "Процент прибыли, оставшейся после вычета всех расходов, включая операционные расходы, проценты, налоги и другие издержки.",
        'return_of_investment': "Мера доходности инвестиции, выраженная в процентах, рассчитанная путем деления чистой прибыли от инвестиции на ее первоначальную стоимость."
    },
    'in': {
        'currency_symbol': 'Rp',
        'average_revenue': "Total pendapatan yang dihasilkan oleh sebuah bisnis dibagi dengan jumlah unit yang dijual atau layanan yang diberikan.",
        'operating_cost': "Total biaya yang dikeluarkan oleh sebuah bisnis dalam operasinya sehari-hari, termasuk biaya tetap dan variabel.",
        'gross_profit': "Perbedaan antara total pendapatan dan biaya barang yang dijual, mewakili keuntungan sebelum dikurangi biaya lainnya.",
        'gross_profit_margin_rate': "Persentase pendapatan yang melebihi biaya barang yang dijual, menunjukkan profitabilitas operasi inti bisnis.",
        'operating_profit_margin_rate': "Persentase keuntungan yang tersisa setelah dikurangi biaya operasional dari laba kotor, mencerminkan efisiensi operasional.",
        'net_profit_margin_rate': "Persentase keuntungan yang tersisa setelah dikurangi semua biaya, termasuk biaya operasional, bunga, pajak, dan biaya lainnya.",
        'return_of_investment': "Sebuah ukuran dari profitabilitas suatu investasi, diungkapkan sebagai persentase, dihitung dengan membagi keuntungan bersih dari investasi dengan biaya awalnya."
    }
    }
    return descriptions.get(nationality, {'error': 'Description not available for this nationality.'})

@app.route('/', methods=['GET', 'POST'])
def home():
    if request.method == 'POST':
        revenue = float(request.form['revenue'])
        units_sold = float(request.form['units_sold'])
        selling_price = float(request.form['selling_price'])
        cost_of_goods_sold = float(request.form['cost_of_goods_sold'])
        operating_expenses = float(request.form['operating_expenses'])
        interest = float(request.form['interest'])
        taxes = float(request.form['taxes'])
        period = request.form['period']
        nationality = request.form['nationality']

        metrics = calculate_metrics(revenue, units_sold, selling_price, cost_of_goods_sold, operating_expenses, interest, taxes, period)
        descriptions = fetch_descriptions(nationality)
        return render_template('result.html', metrics=metrics, descriptions=descriptions)

    return render_template('index.html')

if __name__ == '__main__':
    app.run(debug=True)